apiVersion: v1
kind: Service
metadata:
  name: dfd-dev-node-messaging-srvc
  labels:
    app: dfd-dev-node-messaging
    project: digital-front-door
    release: '1.0'
spec:
  selector:
    app: dfd-dev-node-messaging
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
---

