apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfd-dev-node-messaging-deployment
  namespace: dfd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfd-dev-node-messaging
  strategy:
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: dfd-dev-node-messaging
        project: digital-front-door
        release: '1.0'
      namespace: dfd-system
    spec:     # pod spec                  
      containers: 
      - name: dfd-dev-node-messaging
        image: 829126661606.dkr.ecr.us-east-1.amazonaws.com/dfd-dev-node-messaging:latest
        imagePullPolicy: Always
        command: [ "npm", "start" ]
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   failureThreshold: 30
        #   httpGet:
        #     path: /health/readyness
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 2
        #   successThreshold: 1
        #   timeoutSeconds: 1
        # livenessProbe:
        #   httpGet:
        #     path: /health/liveness
        #     port: 8080
        #     httpHeaders:
        #     - name: Custom-Header
        #       value: Its Alive!
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        # startupProbe:
        #   httpGet:
        #     path: /health/startup
        #     port: 8080
        #   failureThreshold: 30
        #   periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
          - name: RDS_USERNAME
            valueFrom:
              secretKeyRef:
                name: hss-dev-db
                key: RDS_USERNAME
          - name: RDS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hss-dev-db
                key: RDS_PASSWORD
          - name: RDS_HOST
            valueFrom:
              secretKeyRef:
                name: hss-dev-db
                key: RDS_HOST
          - name: RDS_DATABASE
            valueFrom:
              secretKeyRef:
                name: hss-dev-db
                key: RDS_DATABASE
          - name: FORCE
            valueFrom:
              configMapKeyRef:
                name: hss-dev-orm
                key: FORCE
          - name: ALTER
            valueFrom:
              configMapKeyRef:
                name: hss-dev-orm
                key: ALTER
          - name: LOGGING
            valueFrom:
              configMapKeyRef:
                name: hss-dev-orm
                key: LOGGING
          - name: SENDER_EMAIL_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: hss-dev-pinpoint
                key: SENDER_EMAIL_ADDRESS
          - name: REPLY_EMAIL_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: hss-dev-pinpoint
                key: REPLY_EMAIL_ADDRESS
          - name: APP_ID
            valueFrom:
              configMapKeyRef:
                name: hss-dev-pinpoint
                key: APP_ID
          - name: Preferred_Authentication_Method
            valueFrom:
              configMapKeyRef:
                name: hss-dev-pinpoint
                key: Preferred_Authentication_Method
          - name: CHANNEL_TYPE
            valueFrom:
              configMapKeyRef:
                name: hss-dev-pinpoint
                key: CHANNEL_TYPE
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: hss-dev-pinpoint
                key: AWS_REGION
---
