apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hss-dev-cronjob-reminder
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      # Run for duration 900 seconds or 15 minutes
      activeDeadlineSeconds: 900
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: hss-dev-cronjob-reminder
              image: 829126661606.dkr.ecr.us-east-1.amazonaws.com/dfd-dev-node-cronjob-reminders:latest
              imagePullPolicy: Always
              command: [ "npm", "start" ]
              ports:
              - containerPort: 8080
              resources:
                limits:
                  cpu: 2000m
                  memory: 1024Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              env:
                - name: RDS_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: hss-dev-db
                      key: RDS_USERNAME
                - name: RDS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: hss-dev-db
                      key: RDS_PASSWORD
                - name: RDS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: hss-dev-db
                      key: RDS_HOST
                - name: RDS_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: hss-dev-db
                      key: RDS_DATABASE
                - name: FORCE
                  valueFrom:
                    configMapKeyRef:
                      name: hss-dev-orm
                      key: FORCE
                - name: ALTER
                  valueFrom:
                    configMapKeyRef:
                      name: hss-dev-orm
                      key: ALTER
                - name: LOGGING
                  valueFrom:
                    configMapKeyRef:
                      name: hss-dev-orm
                      key: LOGGING
                - name: AWS_COGNITO_USERPOOL_ID
                  valueFrom:
                    secretKeyRef:
                      name: hss-dev-cognito
                      key: AWS_COGNITO_USERPOOL_ID
                - name: AWS_COGNITO_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: hss-dev-cognito
                      key: AWS_COGNITO_CLIENT_ID
                - name: AWS_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: hss-dev-pinpoint
                      key: AWS_REGION
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: AWS_ACCESS_KEY_ID
                - name: SENDER_EMAIL_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      name: hss-dev-pinpoint
                      key: SENDER_EMAIL_ADDRESS
                - name: REPLY_EMAIL_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      name: hss-dev-pinpoint
                      key: REPLY_EMAIL_ADDRESS
                - name: APP_ID
                  valueFrom:
                    configMapKeyRef:
                      name: hss-dev-pinpoint
                      key: APP_ID
                - name: Preferred_Authentication_Method
                  valueFrom:
                    configMapKeyRef:
                      name: hss-dev-pinpoint
                      key: Preferred_Authentication_Method
                - name: CHANNEL_TYPE
                  valueFrom:
                    configMapKeyRef:
                      name: hss-dev-pinpoint
                      key: CHANNEL_TYPE
          restartPolicy: Never