  apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: states-cluster
  region: us-west-2
  version: "1.18"

vpc:
  id: 
  cidr: ""     # (optional, must match CIDR used by the given VPC)
  securityGroup: 
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      us-west-2b:
        id: 
      us-west-2c:
        id: 
      us-west-2d:
        id: 
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
privateCluster:
  enabled: false

iam:
  serviceRoleARN: 
  fargatePodExecutionRoleARN: 
  withOIDC: true

secretsEncryption:
    keyARN: 

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["api","audit", "authenticator", "controllerManager", "scheduler"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"